// Bundles the site's own Next.js route handlers (app/api/**/route.js) into one
// Cloudflare Worker. Imports that only work on Node/Vercel are swapped for the
// shims in src/shims (Firestore over REST, NextResponse, next/cache).
import { build } from "esbuild";
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const apiDir = resolve(here, "../app/api");

import site from "./site.config.mjs";

function routes(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...routes(p));
    else if (/^route\.jsx?$/.test(name)) out.push(p);
  }
  return out;
}

const table = routes(apiDir)
  .map((file) => ({ file, path: relative(apiDir, dirname(file)) }))
  .filter(({ path }) => !site.skip.some((re) => re.test(path)))
  .sort((a, b) => a.path.localeCompare(b.path));

const gen = [
  "// Generated by build.mjs. Do not edit.",
  ...table.map((r, i) => `import * as r${i} from ${JSON.stringify(relative(join(here, "src"), r.file))};`),
  "export const routes = [",
  ...table.map((r, i) => {
    const params = [];
    const re = r.path.split("/").map((seg) => {
      const m = /^\[(\w+)\]$/.exec(seg);
      if (!m) return seg.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      params.push(m[1]);
      return "([^/]+)";
    }).join("/");
    return `  { path: ${JSON.stringify(r.path)}, re: /^\\/api\\/${re.replace(/\//g, "\\/")}\\/?$/, params: ${JSON.stringify(params)}, mod: r${i} },`;
  }),
  "];",
  `export const site = ${JSON.stringify({ origins: site.origins, cache: site.cache })};`,
].join("\n");
const genFile = join(here, "src/routes.gen.js");
// Only rewrite on change: wrangler dev watches src/ and would rebuild forever.
if (!existsSync(genFile) || readFileSync(genFile, "utf8") !== gen + "\n") writeFileSync(genFile, gen + "\n");

// Data files the libs read with fs.readFileSync, embedded as strings.
const dataDir = resolve(here, "../data");
const embedded = {};
if (existsSync(dataDir)) {
  for (const name of readdirSync(dataDir).filter((f) => f.endsWith(".json") && !(site.data?.exclude || []).includes(f))) {
    let value = JSON.parse(readFileSync(join(dataDir, name), "utf8"));
    const keep = site.data?.trim?.[name];
    if (keep && Array.isArray(value)) value = value.map((e) => Object.fromEntries(keep.filter((k) => e[k] !== undefined).map((k) => [k, e[k]])));
    embedded[name] = JSON.stringify(value);
  }
}
const dataGen = `// Generated by build.mjs. Do not edit.\nexport default ${JSON.stringify(embedded)};\n`;
const dataFile = join(here, "src/data.gen.js");
if (!existsSync(dataFile) || readFileSync(dataFile, "utf8") !== dataGen) writeFileSync(dataFile, dataGen);

const shims = {
  "next/server": join(here, "src/shims/next-server.js"),
  "next/cache": join(here, "src/shims/next-cache.js"),
  "firebase-admin/firestore": join(here, "src/shims/firebase-admin-firestore.js"),
  "firebase-admin/storage": join(here, "src/shims/firebase-admin-storage.js"),
  "firebase-admin/app": join(here, "src/shims/firebase-admin-app.js"),
  "firebase-admin/auth": join(here, "src/shims/firebase-admin-auth.js"),
};
const NODE = /^(node:)?(crypto|fs|path|buffer|stream|util|events|url|zlib|os|async_hooks)$/;

await build({
  entryPoints: [join(here, "src/index.js")],
  outfile: join(here, "dist/index.js"),
  bundle: true,
  format: "esm",
  platform: "neutral",
  target: "es2022",
  mainFields: ["module", "main"],
  conditions: ["worker", "browser", "import", "default"],
  minify: true,
  loader: { ".js": "jsx", ".jsx": "jsx" },
  metafile: true,
  logLevel: "error",
  // lib/siteData.js resolves paths from import.meta.url; the virtual fs only matches file names.
  define: { "import.meta.url": JSON.stringify("file:///bundle/lib/module.js") },
  plugins: [{
    name: "worker-shims",
    setup(b) {
      b.onResolve({ filter: /.*/ }, (args) => {
        if (shims[args.path]) return { path: shims[args.path] };
        if (/(^|\/)firebaseAdmin(\.js)?$/.test(args.path) && !args.importer.includes("/api-worker/")) return { path: join(here, "src/shims/firebaseAdmin.js") };
        if (/^(node:)?fs$/.test(args.path) && !args.importer.includes("/api-worker/")) return { path: join(here, "src/shims/fs.js") };
        const m = NODE.exec(args.path);
        if (m) return { path: `node:${m[2]}`, external: true };
        if (/^firebase-admin(\/|$)/.test(args.path)) throw new Error(`firebase-admin import left in ${args.importer}`);
        return undefined;
      });
    },
  }],
}).then((r) => {
  const bytes = Object.values(r.metafile.outputs).reduce((n, o) => n + o.bytes, 0);
  console.log(`worker bundle: ${table.length} routes, ${(bytes / 1024).toFixed(0)} KiB`);
  const big = Object.entries(r.metafile.inputs).sort((a, b) => b[1].bytes - a[1].bytes).slice(0, 6);
  for (const [f, i] of big) console.log(`  ${(i.bytes / 1024).toFixed(0).padStart(6)} KiB  ${f}`);
});
