import { getSiteUrl } from "./site-url.js";

export const TELANGANA_COLLEGES = [
  {
    slug: "cbit-hyderabad",
    name: "Chaitanya Bharathi Institute of Technology (CBIT)",
    shortName: "CBIT Hyderabad",
    location: "Gandipet, Hyderabad",
    established: 1979,
    tier: "Tier 2 (Top State Autonomous)",
    nirfRankBand: "Rank 101–150 (NIRF Engineering)",
    overview:
      "CBIT is widely regarded as one of Telangana's premier private engineering institutions with a 45-year legacy. Located in Gandipet near Financial District, CBIT hosts major product and GCC recruiters annually.",
    stats: {
      batchSize: 1560,
      placedCount: 756,
      placementRate: "68%",
      medianCTC: "₹6.0 LPA",
      highestCTC: "₹54.0 LPA",
      totalOffers: "950+",
    },
    salaryDistribution: [
      {
        lpaBand: "> ₹15.0 LPA",
        category: "Super Dream / Top Product & GCCs",
        studentCount: 65,
        percentage: "4.2%",
        companies: "Microsoft, ServiceNow, JPMC, Oracle OCI",
        description: "Direct campus shortlists for top 5% coding rankers and ACM-ICPC finalists.",
      },
      {
        lpaBand: "₹8.0 – ₹15.0 LPA",
        category: "Dream / SaaS Startups & Financial GCCs",
        studentCount: 195,
        percentage: "12.5%",
        companies: "Darwinbox, Keka HR, Wells Fargo, HighRadius, FactSet",
        description: "Full-stack development, SDE-1, and data engineering core roles.",
      },
      {
        lpaBand: "₹5.0 – ₹8.0 LPA",
        category: "Differential IT Services / Trainee Dev",
        studentCount: 310,
        percentage: "19.8%",
        companies: "TCS Digital, Cognizant GenC Elevate, Accenture Advanced",
        description: "Advanced service company bands tested on DSA and modern stack.",
      },
      {
        lpaBand: "₹3.36 – ₹4.5 LPA",
        category: "Mass Recruiter Baseline",
        studentCount: 380,
        percentage: "24.3%",
        companies: "TCS Ninja, Infosys, Capgemini, Cognizant",
        description: "Standard service intakes for general software testing and maintenance.",
      },
      {
        lpaBand: "Unplaced / Off-Campus",
        category: "Off-Campus Search & Higher Studies",
        studentCount: 610,
        percentage: "39.1%",
        companies: "Direct ATS applications, MS in US, GATE prep",
        description: "Graduates competing in Hyderabad off-campus startup and GCC market.",
      },
    ],
    topRecruiters: [
      "Microsoft",
      "ServiceNow",
      "JPMC",
      "Wells Fargo",
      "Oracle",
      "Keka HR",
      "Darwinbox",
      "Cognizant",
      "TCS Digital",
    ],
    alumniStartups: ["Keka HR", "Edvizo", "Acrobits", "Smartbridge"],
    faq: [
      {
        question: "What is the average and median placement package at CBIT Hyderabad?",
        answer:
          "For the 2024–2026 batches, the median salary at CBIT stands at ₹6.0 LPA, with top product offers from Microsoft, ServiceNow, and JPMC reaching ₹40 LPA to ₹54 LPA.",
      },
      {
        question: "Which companies recruit the highest number of students from CBIT?",
        answer:
          "Major mass recruiters include Cognizant and TCS, while top product recruiters include ServiceNow, JPMC, Oracle, Wells Fargo, and Hyderabad SaaS startups like Keka and Darwinbox.",
      },
    ],
  },
  {
    slug: "vnr-vjiet-hyderabad",
    name: "VNR Vignana Jyothi Institute of Engineering & Technology",
    shortName: "VNR VJIET",
    location: "Bachupally, Nizampet, Hyderabad",
    established: 1995,
    tier: "Tier 2 (Top State Autonomous)",
    nirfRankBand: "Rank 101–150 (NIRF Engineering)",
    overview:
      "VNR VJIET in Bachupally is known for exceptional campus placement volumes, consistently generating over 2,000 offers across product companies, GCCs, and IT service giants.",
    stats: {
      batchSize: 2100,
      placedCount: 1107,
      placementRate: "72%",
      medianCTC: "₹6.5 LPA",
      highestCTC: "₹92.0 LPA",
      totalOffers: "2,112 offers",
    },
    salaryDistribution: [
      {
        lpaBand: "> ₹15.0 LPA",
        category: "Super Dream / Product Giants",
        studentCount: 95,
        percentage: "4.5%",
        companies: "Amazon, Oracle OCI, ServiceNow, JPMC",
        description: "Top 4–5% coders with strong LeetCode rankings and hackathon wins.",
      },
      {
        lpaBand: "₹8.0 – ₹15.0 LPA",
        category: "Dream / Scaleups & GCCs",
        studentCount: 280,
        percentage: "13.3%",
        companies: "Darwinbox, NCR Voyix, Wells Fargo, Providence India",
        description: "Core backend SDE-1, Cloud, and Fintech engineering roles.",
      },
      {
        lpaBand: "₹5.0 – ₹8.0 LPA",
        category: "Differential IT Services",
        studentCount: 510,
        percentage: "24.3%",
        companies: "TCS Digital, Accenture Advanced, Deloitte USI",
        description: "Specialized enterprise dev and technical analyst hiring.",
      },
      {
        lpaBand: "₹3.36 – ₹4.5 LPA",
        category: "Mass Recruiter Baseline",
        studentCount: 640,
        percentage: "30.5%",
        companies: "TCS Ninja, Capgemini, Infosys, Tech Mahindra",
        description: "Large volume campus placement offers in software testing/maintenance.",
      },
      {
        lpaBand: "Unplaced / Off-Campus",
        category: "Off-Campus Search & Higher Studies",
        studentCount: 575,
        percentage: "27.4%",
        companies: "Direct startup ATS, MS admissions, Off-campus pool drives",
        description: "Graduates seeking off-campus roles or pursuing international MS degrees.",
      },
    ],
    topRecruiters: [
      "Amazon",
      "Oracle OCI",
      "ServiceNow",
      "JPMorgan Chase",
      "Darwinbox",
      "NCR Voyix",
      "TCS Digital",
      "Accenture",
      "Capgemini",
    ],
    alumniStartups: ["StreetByte", "Recykal (alumni engineers)", "VisiAI"],
    faq: [
      {
        question: "How many offers does VNR VJIET receive during campus placements?",
        answer:
          "VNR VJIET students regularly secure over 2,000 total placement offers per academic year, with over 1,100 unique students placed across product and service firms.",
      },
      {
        question: "What is the highest package offered at VNR VJIET?",
        answer:
          "The highest international/product package reached ₹92 LPA, with regular domestic top packages ranging from ₹45 LPA to ₹65 LPA from Amazon and Oracle.",
      },
    ],
  },
  {
    slug: "vasavi-college-hyderabad",
    name: "Vasavi College of Engineering (VCE)",
    shortName: "Vasavi College",
    location: "Ibrahimbagh, Hyderabad",
    established: 1981,
    tier: "Tier 2 (Top State Autonomous)",
    nirfRankBand: "Rank 151–200 (NIRF Engineering)",
    overview:
      "Affiliated with Osmania University and located in Ibrahimbagh, Vasavi College is celebrated for strong coding culture and consistent high-package placements at ServiceNow and Oracle.",
    stats: {
      batchSize: 960,
      placedCount: 551,
      placementRate: "66.7%",
      medianCTC: "₹5.8 LPA",
      highestCTC: "₹47.5 LPA",
      totalOffers: "780+",
    },
    salaryDistribution: [
      {
        lpaBand: "> ₹15.0 LPA",
        category: "Super Dream / Top Product",
        studentCount: 42,
        percentage: "4.4%",
        companies: "ServiceNow, Oracle OCI, Cisco Systems",
        description: "Premier coding achievers placed in core product engineering.",
      },
      {
        lpaBand: "₹8.0 – ₹15.0 LPA",
        category: "Dream / SaaS & GCCs",
        studentCount: 125,
        percentage: "13.0%",
        companies: "Darwinbox, HighRadius, FactSet, Providence",
        description: "Full-stack SaaS development and financial analytics.",
      },
      {
        lpaBand: "₹5.0 – ₹8.0 LPA",
        category: "Differential IT Services",
        studentCount: 210,
        percentage: "21.9%",
        companies: "TCS Digital, Cognizant GenC Elevate",
        description: "Specialized developer hiring tracks.",
      },
      {
        lpaBand: "₹3.36 – ₹4.5 LPA",
        category: "Mass Recruiter Baseline",
        studentCount: 260,
        percentage: "27.1%",
        companies: "Infosys, Accenture, TCS Ninja",
        description: "Baseline software engineering and QA profiles.",
      },
      {
        lpaBand: "Unplaced / Off-Campus",
        category: "Off-Campus Search & Higher Studies",
        studentCount: 323,
        percentage: "33.6%",
        companies: "Off-campus ATS applications, MS in USA/Germany",
        description: "Graduates preparing for off-campus startup rounds and GATE.",
      },
    ],
    topRecruiters: [
      "ServiceNow",
      "Oracle",
      "Cisco",
      "Darwinbox",
      "HighRadius",
      "FactSet",
      "Infosys",
      "Accenture",
    ],
    alumniStartups: ["Zaggle (leadership alumni)", "Graphene AI"],
    faq: [
      {
        question: "What is the placement percentage at Vasavi College of Engineering?",
        answer:
          "According to NIRF disclosures, Vasavi records a placement rate of 66.7% for eligible graduating students, with a median package of ₹5.8 LPA.",
      },
    ],
  },
  {
    slug: "jntuh-hyderabad",
    name: "JNTUH University College of Engineering Hyderabad",
    shortName: "JNTUH CEH",
    location: "Kukatpally, Hyderabad",
    established: 1965,
    tier: "Tier 2 (Premier State University Campus)",
    nirfRankBand: "Rank 83 (NIRF Engineering)",
    overview:
      "The flagship engineering campus of Jawaharlal Nehru Technological University, located in Kukatpally right on the Hyderabad Metro corridor. Top destination for core engineering and software recruits.",
    stats: {
      batchSize: 1100,
      placedCount: 630,
      placementRate: "65%",
      medianCTC: "₹6.0 LPA",
      highestCTC: "₹52.0 LPA",
      totalOffers: "750+",
    },
    salaryDistribution: [
      {
        lpaBand: "> ₹15.0 LPA",
        category: "Super Dream / Semiconductor & Systems",
        studentCount: 70,
        percentage: "6.4%",
        companies: "AMD, Qualcomm, MathWorks, Honeywell",
        description: "Silicon design, embedded systems, and systems software engineering.",
      },
      {
        lpaBand: "₹8.0 – ₹15.0 LPA",
        category: "Core R&D & Product",
        studentCount: 165,
        percentage: "15.0%",
        companies: "Oracle, TCS Digital, BHEL R&D, Tech Mahindra R&D",
        description: "Core engineering R&D and advanced enterprise applications.",
      },
      {
        lpaBand: "₹5.0 – ₹8.0 LPA",
        category: "Differential IT & Core Industry",
        studentCount: 235,
        percentage: "21.4%",
        companies: "TCS Digital, Cognizant, Medha Servo Drives",
        description: "Embedded electronics and software solutions.",
      },
      {
        lpaBand: "₹3.36 – ₹4.5 LPA",
        category: "Mass Recruiter Baseline",
        studentCount: 260,
        percentage: "23.6%",
        companies: "TCS Ninja, Wipro, Infosys",
        description: "Standard service intakes.",
      },
      {
        lpaBand: "Unplaced / Higher Studies / Govt",
        category: "GATE / PSU / Off-Campus",
        studentCount: 370,
        percentage: "33.6%",
        companies: "GATE M.Tech (IITs), TSPSC / UPSC / ISRO prep",
        description: "Significant share actively pursues central/state govt exams and GATE.",
      },
    ],
    topRecruiters: [
      "AMD",
      "Qualcomm",
      "MathWorks",
      "Honeywell",
      "TCS",
      "Tech Mahindra",
      "BHEL",
    ],
    alumniStartups: ["Skyroot Aerospace (Pawan Chandana alumni connection)", "Dhruva Space"],
    faq: [
      {
        question: "Why is JNTUH CEH favored by semiconductor and hardware companies?",
        answer:
          "JNTUH Kukatpally has premier R&D labs and strong ECE/EEE departments that attract top semiconductor giants like AMD, Qualcomm, and Intel for chip design and embedded software roles.",
      },
    ],
  },
  {
    slug: "iiit-hyderabad",
    name: "International Institute of Information Technology Hyderabad",
    shortName: "IIIT Hyderabad",
    location: "Gachibowli, Hyderabad",
    established: 1998,
    tier: "Tier 1 (National Premier Research)",
    nirfRankBand: "Rank 14–16 (NIRF Engineering 2024) / Top 5 CS Research in India",
    overview:
      "One of India's premier autonomous research universities in computer science, computer vision, AI, and systems engineering. Houses the Centre for Innovation and Entrepreneurship (CIE).",
    stats: {
      batchSize: 450,
      placedCount: 390,
      placementRate: "88%",
      medianCTC: "₹32.0 LPA (B.Tech CSE)",
      highestCTC: "₹1.02 Crore+",
      totalOffers: "500+",
    },
    salaryDistribution: [
      {
        lpaBand: "> ₹30.0 LPA",
        category: "Global Tech Giants & HFT Quant",
        studentCount: 170,
        percentage: "37.8%",
        companies: "Google, Uber, DE Shaw, Tower Research, Apple, Meta",
        description: "Premier algorithmic trading, research engineering, and global tech roles.",
      },
      {
        lpaBand: "₹18.0 – ₹30.0 LPA",
        category: "Tier-1 Product & AI Research",
        studentCount: 150,
        percentage: "33.3%",
        companies: "NVIDIA, Adobe, Qualcomm, Microsoft, Rubrik",
        description: "Deep learning, GPU systems, systems programming, and high-scale backend.",
      },
      {
        lpaBand: "₹10.0 – ₹18.0 LPA",
        category: "High-Growth Startups & Scaleups",
        studentCount: 70,
        percentage: "15.5%",
        companies: "Funded AI startups, CIE-incubated deeptech ventures",
        description: "Direct founder hiring and core product development.",
      },
      {
        lpaBand: "Higher Studies / Research",
        category: "MS / PhD / Direct Research Labs",
        studentCount: 60,
        percentage: "13.3%",
        companies: "CMU, Stanford, EPFL, Max Planck, IIIT-H Research Labs",
        description: "Graduates pursuing academic and industrial AI research.",
      },
    ],
    topRecruiters: [
      "Google",
      "Apple",
      "Uber",
      "Meta",
      "Tower Research",
      "DE Shaw",
      "Adobe",
      "NVIDIA",
      "Qualcomm",
    ],
    alumniStartups: ["TakeMe2Space", "Logy.AI", "Perceptyne", "Harvested Robotics", "Aganitha AI"],
    faq: [
      {
        question: "What is the average salary at IIIT Hyderabad?",
        answer:
          "B.Tech CSE graduates at IIIT Hyderabad command a median CTC of ₹32.0 LPA, with top domestic packages exceeding ₹65 LPA and international HFT offers crossing ₹1 Crore+.",
      },
    ],
  },
  {
    slug: "iit-hyderabad",
    name: "Indian Institute of Technology Hyderabad",
    shortName: "IIT Hyderabad",
    location: "Kandi, Sangareddy, Hyderabad Outer",
    established: 2008,
    tier: "Tier 1 (Institute of National Importance)",
    nirfRankBand: "Rank 8 (NIRF Engineering)",
    overview:
      "Ranked #8 in India, IIT Hyderabad is a global powerhouse for deeptech, semiconductor research, quantum computing, and AI systems with extensive Japanese industry collaborations.",
    stats: {
      batchSize: 750,
      placedCount: 460,
      placementRate: "62%",
      medianCTC: "₹20.0 LPA",
      highestCTC: "₹90.0 LPA+",
      totalOffers: "600+",
    },
    salaryDistribution: [
      {
        lpaBand: "> ₹25.0 LPA",
        category: "Global Product & Japanese Giants",
        studentCount: 140,
        percentage: "18.7%",
        companies: "Google, Microsoft, TSMC, Goldman Sachs, Rakuten",
        description: "Top-tier international tech hiring and core algorithmic development.",
      },
      {
        lpaBand: "₹15.0 – ₹25.0 LPA",
        category: "Semiconductors & DeepTech GCCs",
        studentCount: 190,
        percentage: "25.3%",
        companies: "Texas Instruments, NVIDIA, Sony Japan, Qualcomm",
        description: "VLSI chip design, embedded computing, and autonomous systems.",
      },
      {
        lpaBand: "₹8.0 – ₹15.0 LPA",
        category: "Core Engineering & Product Startups",
        studentCount: 130,
        percentage: "17.3%",
        companies: "Pure EV, Mid-tier GCCs, Aerospace & EV startups",
        description: "Specialized mechanical, chemical, and EV engineering.",
      },
      {
        lpaBand: "Higher Studies / Public Sector / Research",
        category: "Direct PhD / PSU / Research Fellowships",
        studentCount: 290,
        percentage: "38.7%",
        companies: "Foreign Universities, ISRO/DRDO, Japanese University partnerships",
        description: "Extensive student body opting for direct research tracks.",
      },
    ],
    topRecruiters: [
      "Google",
      "Microsoft",
      "Rakuten",
      "Sony Japan",
      "TSMC",
      "NVIDIA",
      "Goldman Sachs",
      "Texas Instruments",
    ],
    alumniStartups: ["Pure EV (IIT-H incubated)", "PuRE Energy"],
    faq: [
      {
        question: "What companies recruit from IIT Hyderabad?",
        answer:
          "IIT Hyderabad hosts over 150+ domestic and international recruiters including Japanese tech giants (Rakuten, Sony, Suzuki), global tech firms (Google, Microsoft), and hardware innovators (Texas Instruments, NVIDIA).",
      },
    ],
  },
  {
    slug: "cvr-college-hyderabad",
    name: "CVR College of Engineering",
    shortName: "CVR College",
    location: "Vastunagar, Mangalpalli, Ibrahimpatnam",
    established: 2001,
    tier: "Tier 2 (Top State Autonomous)",
    nirfRankBand: "Rank 151–200 (NIRF Engineering)",
    overview:
      "Located in Vastunagar, CVR College is a renowned autonomous engineering college in Telangana with rigorous academic discipline and strong IT service placements.",
    stats: {
      batchSize: 1300,
      placedCount: 710,
      placementRate: "58%",
      medianCTC: "₹5.2 LPA",
      highestCTC: "₹38.0 LPA",
      totalOffers: "900+",
    },
    salaryDistribution: [
      {
        lpaBand: "> ₹12.0 LPA",
        category: "Super Dream / Product Shortlist",
        studentCount: 30,
        percentage: "2.3%",
        companies: "Darwinbox, Virtusa Pro, Product Startups",
        description: "Top coding achievers securing direct product offers.",
      },
      {
        lpaBand: "₹7.0 – ₹12.0 LPA",
        category: "Differential Service & SaaS",
        studentCount: 120,
        percentage: "9.2%",
        companies: "Cognizant GenC Next, Accenture Advanced, Tech Mahindra Pro",
        description: "Specialized developer hiring.",
      },
      {
        lpaBand: "₹4.5 – ₹7.0 LPA",
        category: "Standard Developer Hiring",
        studentCount: 260,
        percentage: "20.0%",
        companies: "Capgemini, Virtusa, TCS Digital",
        description: "Software engineer and testing tracks.",
      },
      {
        lpaBand: "₹3.36 – ₹4.5 LPA",
        category: "Mass Recruiter Baseline",
        studentCount: 300,
        percentage: "23.1%",
        companies: "Cognizant, TCS Ninja, Accenture",
        description: "Core campus intake baseline.",
      },
      {
        lpaBand: "Unplaced / Off-Campus",
        category: "Off-Campus Search & Higher Studies",
        studentCount: 590,
        percentage: "45.4%",
        companies: "Off-campus ATS applications, Ameerpet upskilling, MS prep",
        description: "Graduates pursuing off-campus startup openings.",
      },
    ],
    topRecruiters: [
      "Cognizant",
      "Capgemini",
      "Virtusa",
      "Accenture",
      "TCS",
      "Darwinbox",
      "Tech Mahindra",
    ],
    alumniStartups: [],
    faq: [
      {
        question: "What is the average package at CVR College of Engineering?",
        answer:
          "The average compensation package at CVR College ranges between ₹4.8 LPA and ₹5.5 LPA, with top software development offers reaching ₹30 LPA+.",
      },
    ],
  },
  {
    slug: "griet-hyderabad",
    name: "Gokaraju Rangaraju Institute of Engineering & Technology",
    shortName: "GRIET Hyderabad",
    location: "Bachupally, Kukatpally, Hyderabad",
    established: 1997,
    tier: "Tier 2 (Top State Autonomous)",
    nirfRankBand: "Rank 101–150 (NIRF Engineering)",
    overview:
      "Situated in Bachupally, GRIET is a premier autonomous engineering college known for active student clubs, coding hackathons, and high-volume campus hiring by Tier-1 IT companies.",
    stats: {
      batchSize: 1400,
      placedCount: 780,
      placementRate: "62%",
      medianCTC: "₹5.5 LPA",
      highestCTC: "₹44.0 LPA",
      totalOffers: "1,050+",
    },
    salaryDistribution: [
      {
        lpaBand: "> ₹15.0 LPA",
        category: "Super Dream / Top Tech",
        studentCount: 38,
        percentage: "2.7%",
        companies: "Amazon, ServiceNow, Hexagon",
        description: "Top competitive programmers placed at tech giants.",
      },
      {
        lpaBand: "₹8.0 – ₹15.0 LPA",
        category: "Dream / Scaleups & GCCs",
        studentCount: 155,
        percentage: "11.1%",
        companies: "Darwinbox, TCS Digital, NCR Voyix, Cognizant Next",
        description: "Fullstack engineering and cloud development.",
      },
      {
        lpaBand: "₹5.0 – ₹8.0 LPA",
        category: "Differential IT Services",
        studentCount: 310,
        percentage: "22.1%",
        companies: "Accenture, Cognizant Elevate, TCS Digital",
        description: "Core technical development tracks.",
      },
      {
        lpaBand: "₹3.36 – ₹4.5 LPA",
        category: "Mass Recruiter Baseline",
        studentCount: 277,
        percentage: "19.8%",
        companies: "TCS Ninja, Capgemini, Infosys",
        description: "Standard service intakes.",
      },
      {
        lpaBand: "Unplaced / Off-Campus",
        category: "Off-Campus Search & Higher Studies",
        studentCount: 620,
        percentage: "44.3%",
        companies: "Direct startup ATS, MS abroad, GATE prep",
        description: "Graduates competing in Hyderabad off-campus tech market.",
      },
    ],
    topRecruiters: [
      "Amazon",
      "TCS Digital",
      "Accenture",
      "Cognizant",
      "ServiceNow",
      "Darwinbox",
      "Hexagon",
    ],
    alumniStartups: [],
    faq: [
      {
        question: "What is the placement record of GRIET Hyderabad?",
        answer:
          "GRIET consistently achieves over 1,000 total job offers per year with a median package of ₹5.5 LPA and highest offers exceeding ₹40 LPA.",
      },
    ],
  },
];

export function getCollegeBySlug(slug) {
  return TELANGANA_COLLEGES.find((c) => c.slug === slug) || null;
}
